default:
  image: golang:1.16.5-alpine

stages:
  - lint
  - test


lint:
  stage: lint
  script:
    - |
      FILES=$(gofmt -s -l .)
      if [ -n "${FILES}" ]; then
          printf "Following files are not formatted: \n%s" "$FILES"
          exit 1
      fi

build:
  stage: test
  before_script:
    - apk add make build-base
  script:
    - make test
