{{ if and .Values.secret.accessKey .Values.secret.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "pinto-webhook.name" . }}
    chart: {{ include "pinto-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  SCW_ACCESS_KEY: {{ .Values.secret.accessKey }}
  SCW_SECRET_KEY: {{ .Values.secret.secretKey }}
{{ end }}
