{{ if or .Values.secret.accessKey .Values.secret.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "pinto-webhook.name" . }}
    chart: {{ include "pinto-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{ if .Values.secret.accessKey -}}PINTO_OAUTH_CLIENT_ID: {{ .Values.secret.accessKey }}{{- end }}
  {{ if .Values.secret.secretKey -}}PINTO_OAUTH_CLIENT_SECRET: {{ .Values.secret.secretKey }}{{- end }}
{{ end }}
